version: '3'
services:
  # nginx
  nginx:
    container_name: ${APP_NAME}-nginx
    build:
      context: ./
      dockerfile: config/nginx/Dockerfile
    volumes:
      - ${WEB_ROOT}:/var/www/html
      - ./log/nginx/:/var/log/nginx/
    ports:
      - "${NGINX_HTTP_PORT}:80"
      - "${NGINX_HTTPS_PORT}:443"
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
    depends_on:
      - php
      - supervisor
    restart: always
    networks:
      - noplin

  # php
  php:
    container_name: ${APP_NAME}-php
    build:
      context: ./
      dockerfile: config/php/Dockerfile
    volumes:
      - ${WEB_ROOT}:/var/www/html
      - ./log/php/:/var/log/php/
    expose:
      - 9000
    depends_on:
      - mysql
      - redis
    restart: always
    stdin_open: true
    tty: true
    networks:
      - noplin

  # supervisor
  supervisor:
    container_name: ${APP_NAME}-supervisor
    build:
      context: ./
      dockerfile: config/supervisor/Dockerfile
    volumes:
      - ${WEB_ROOT}:/var/www/html
      - ./log/supervisor/:/var/log/supervisor/
    expose:
      - 9000
      - 9001
    ports:
      - "${HORIZON_PORT}:9001"
    depends_on:
      - php
      - mysql
      - redis
    restart: always
    networks:
      - noplin

  # mysql
  mysql:
    container_name: ${APP_NAME}-mysql
    build:
      context: ./
      dockerfile: config/mysql/Dockerfile
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD="${MYSQL_PASSWORD}"
      - MYSQL_DATABASE=ds
    restart: always
    command:
      --default-authentication-plugin=mysql_native_password
    networks:
      - noplin

  # redis
  redis:
    container_name: ${APP_NAME}-redis
    build:
      context: ./
      dockerfile: config/redis/Dockerfile
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./data/redis:/data
      - ./log/redis/:/var/log/redis/
    environment:
      - TZ=Asia/Shanghai
    command: redis-server /etc/redis/redis.conf --requirepass ${REDIS_PASSWORD}
    restart: always
    networks:
      - noplin

  # phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: ${APP_NAME}-phpmyadmin
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql
    restart: always
    networks:
      - noplin

  # phpredisadmin
  phpredisadmin:
    image: erikdubbelboer/phpredisadmin:latest
    container_name: ${APP_NAME}-phpredisadmin
    ports:
      - "${PHPREDISADMIN_PORT}:80"
    environment:
      - TZ=Asia/Shanghai
      - REDIS_1_HOST=redis
      - REDIS_1_PORT=6379
      - REDIS_1_AUTH=${REDIS_PASSWORD}
      - ADMIN_USER=root
      - ADMIN_PASS=${REDIS_PASSWORD}
    depends_on:
      - redis
    restart: always
    networks:
      - noplin

networks:
  noplin:
    driver: bridge
    name: noplin
